/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.student.project;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public  void start(Stage primaryStage) throws Exception {

    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}
